<?php
    echo $this->partial('/partials/menu');
?>
<?php $title = 'Delete a contact'; ?>
<h1><?php echo $this->translate($title); ?></h1>
<br>
<?php
$url = $this->url('siteContact/delete', array('id' => $id));
?>
<form action="<?php echo $url; ?>" method="post">
<div>
    <input type="hidden" name="id" value="<?php echo (int) $id; ?>" />
    <input type="submit" class="btn btn-primary" name="del" value="<?php echo $this->translate('Yes') ?>" />
    &nbsp;&nbsp;
	<a href="<?php echo $this->url('siteContact/index', array('id' => $siteContact->site_id));?>"><?php echo $this->translate('Cancel') ?></a>
</div>
</form>

