<?php
    echo $this->partial('/partials/menu');
?>
<?php
$title = 'Add a contact';

$this->headTitle($title);
?>
<h1><?php echo $this->translate($title); ?></h1>
<h3><?php echo $site->caption; ?></h3>
<table class="table">
	<tr class="<?php echo $this->cycle(array("even", "odd"))->next();?>">
		<td colspan="2">
			<a href="<?php echo $this->url('site');?>"><?php echo $this->translate('Return to sites') ?></a>
		</td>
	</tr>
	<tr >
		<th>&nbsp;</th>
		<th><?php echo $this->translate('Name')?>
	</th>
	<tr class="<?php echo $this->cycle(array("even", "odd"))->next();?>">
		<td colspan="2"><a href="<?php echo $this->url('siteContact/add', array('id' => $id));?>"><img height="12" src="/images/plus.png" alt="add contact" /></a></td>
	</tr>
	    

<?php foreach ($sitecontacts as $sitecontact) : ?>
	<?php if ($sitecontact->is_main_contact) $styleText = 'style="font-weight: bold"'; else $styleText=''; ?>
	<tr class="<?php echo $this->cycle(array("even", "odd"))->next();?>">
	  <td><a href="<?php echo $this->url('siteContact/delete', array('id' => $sitecontact->id));?>"><img height="12" src="/images/eraser.png" alt="Delete" /></a></td>
	  <td <?php echo $styleText ?>><?php echo $this->escapeHtml($sitecontact->n_fn);?></td>
	    
	</tr>
<?php endforeach; ?>
</table>
