<?php
    echo $this->partial('/partials/menu');
?>
<?php
$title = 'Add an order row';
$this->headTitle($title);
?>
<h1><?php echo $this->translate($title); ?></h1>
<h3><?php echo $this->translate('Order number').': '.$order->identifier.'-'.sprintf('%1$06d', $order->id)?></h3>
<?php
    echo $this->partial('/partials/generic-form', array('route' => 'orderProduct/add', 'form' => $this->form, 'id'=>$id, 'returnUrl' => $this->url('orderProduct/index', array('id' => $id))));
?>

<script>
function displayBrandModel() {
<?php foreach ($products as $product) : ?>
	if (document.getElementById("product_id").value == "<?php echo $product->id ?>") {
		document.getElementById("brand").value = "<?php echo $product->brand ?>";
		document.getElementById("model").value = "<?php echo $product->model ?>";
		document.getElementById("price").value = "<?php echo $product->price ?>";
	}
<?php endforeach;?>
}
</script>