<?php
    echo $this->partial('/partials/menu');
?>
<?php

$title = 'Delete an order row';
$this->headTitle($title);
?>
<h1><?php echo $this->translate($title); ?></h1>
<h3><?php echo $this->translate('Order number').': '.$order->identifier.'-'.sprintf('%1$06d', $order->id)?></h3>
<h3><?php echo $this->translate('Product').': '.$product->caption ?></h3>
<br>
<?php
$url = $this->url('orderProduct/delete', array('id' => $this->id));
?>
<form action="<?php echo $url; ?>" method="post">
<div>
    <input type="hidden" name="id" value="<?php echo (int) $this->id; ?>" />
    <input type="submit" class="btn btn-primary" name="del" value="<?php echo $this->translate('Yes') ?>" />
    &nbsp;&nbsp;
	<a href="<?php echo $this->url('orderProduct/index', array('id' => $order->id));?>"><?php echo $this->translate('Cancel') ?></a>
</div>
</form>

