<?php
    echo $this->partial('/partials/menu');
?>
<?php
$title = 'Stocks';
$this->headTitle($title);
?>
<h1><?php echo $this->translate($title); ?></h1>
<table class="table">
	<tr class="<?php echo $this->cycle(array("even", "odd"))->next();?>">
		<td colspan="8">
			<a href="<?php echo $this->url('link/index', array('id' => 2));?>"><?php echo $this->translate('CSV imports') ?></a>
		</td>
	</tr>
	<tr class="<?php echo $this->cycle(array("even", "odd"))->next();?>">
		<td>&nbsp;</td>
		<td>&nbsp;</td>
		<td><strong><a href="<?php echo $this->url('stock') ?>
											?major=caption
											<?php if ($major == 'caption' && $dir =='ASC') echo '&dir=DESC'; else echo '&dir=ASC' ?>">
			<?php echo $this->translate('Caption');?></strong></td>
		<td align="center"><strong><a href="<?php echo $this->url('stock') ?>
											?major=brand
											<?php if ($major == 'brand' && $dir =='ASC') echo '&dir=DESC'; else echo '&dir=ASC' ?>">
			<?php echo $this->translate('Brand');?></strong></td>
		<td align="center"><strong><a href="<?php echo $this->url('stock') ?>
											?major=model
											<?php if ($major == 'model' && $dir =='ASC') echo '&dir=DESC'; else echo '&dir=ASC' ?>">
			<?php echo $this->translate('Model');?></strong></td>
		<td align="center"><strong><a href="<?php echo $this->url('stock') ?>
											?major=identifier
											<?php if ($major == 'identifier' && $dir =='ASC') echo '&dir=DESC'; else echo '&dir=ASC' ?>">
			<?php echo $this->translate('Identifier');?></strong></td>
		<td align="center"><strong><a href="<?php echo $this->url('stock') ?>
											?major=serial_number
											<?php if ($major == 'serial_number' && $dir =='ASC') echo '&dir=DESC'; else echo '&dir=ASC' ?>">
			<?php echo $this->translate('Serial number');?></strong></td>
		<td align="center"><strong><a href="<?php echo $this->url('stock') ?>
											?major=exploitation_date
											<?php if ($major == 'exploitation_date' && $dir =='ASC') echo '&dir=DESC'; else echo '&dir=ASC' ?>">
			<?php echo $this->translate('Exploitation date');?></strong></td>
	</tr>
	<tr>
		<td colspan="8"><a href="<?php echo $this->url('stock/add');?>"><img height="12" src="/images/plus.png" alt="<?php echo $this->translate('Add') ?>" /></a></td>
	</tr>
<?php foreach ($stocks as $stock) : ?>
	<tr>
	<?php if (!$stock->order_id) :?>
		<td><a href="<?php echo $this->url('stock/update', array('id' => $stock->id));?>"><img height="12" src="/images/edit_2.png" alt="<?php echo $this->translate('update') ?>" /></a></td>
		<td><a href="<?php echo $this->url('stock/delete', array('id' => $stock->id));?>"><img height="12" src="/images/eraser.png" alt="<?php echo $this->translate('Delete') ?>" /></a></td>
	<?php else : ?>
		<td colspan="2">&nbsp;</td>
	<?php endif;?>
		<td><?php echo $stock->caption ?></td>
		<td align="center"><?php echo $stock->brand ?></td>
		<td align="center"><?php echo $stock->model ?></td>
		<td align="center"><?php echo $stock->identifier ?></td>
		<td align="center"><?php echo $stock->serial_number ?></td>
		<td align="center"><?php echo $stock->exploitation_date ?></td>
	</tr>
<?php endforeach; ?>
</table>