<?php
    echo $this->partial('/partials/menu');
?>
<?php
$title = 'Localize a stock unit';
$this->headTitle($title);
?>
<h1><?php echo $this->translate($title); ?></h1>
<?php if ($product) : ?>
<h3><?php echo $this->translate('Caption: '.$product->caption) ?></h3>
<p><?php echo $this->translate('Brand: '.$product->brand) ?></p>
<p><?php echo $this->translate('Model: '.$product->model) ?></p>
<?php endif;?>
<p><?php echo $this->translate('Identifier: '.$stock->identifier) ?></p>
<p><?php echo $this->translate('Serial number: '.$stock->serial_number) ?></p>
<?php
    echo $this->partial('/partials/generic-form', array('route' => 'stock/localize', 'form' => $this->form, 'id' => $id, 'returnUrl' => $this->url('stock')));
?>
