<?php
    echo $this->partial('/partials/menu');
?>
<?php
$title = 'CSV imports';
$this->headTitle($title);
?>
<h1><?php echo $this->translate($title); ?></h1>
<h3><?php echo $parent->name; ?></h3>
<table class="table">
        <tr class="<?php echo $this->cycle(array("even", "odd"))->next();?>">
                <td>&nbsp;</td>
                <td>&nbsp;</td>
                <td>&nbsp;</td>
                <td align="center"><strong><a href="<?php echo $this->url($this->route, array('action' => 'index', 'id' => $id)) ?>
                                                                                        ?major=name
                                                                                        <?php if ($major == 'name' && $dir =='ASC') echo '&dir=DESC'; else echo '&dir=ASC' ?>">
                        <?php echo $this->translate('Document name');?></a></strong></td>
                <td align="center"><strong><a href="<?php echo $this->url($this->route, array('action' => 'index', 'id' => $id)) ?>
                                                                                        ?major=uploaded_time
                                                                                        <?php if ($major == 'uploaded_time' && $dir =='ASC') echo '&dir=DESC'; else echo '&dir=ASC' ?>">
                        <?php echo $this->translate('Uploaded');?></a></strong></td>
        </tr>
        <tr>
                <td colspan="5"><a href="<?php echo $this->url('link/add', array('id' => $id));?>"><img height="12" src="/images/plus.png" alt="<?php echo $this->translate('Add') ?>" /></a></td>
        </tr>
<?php 
	if ($parent->id == 0) $targetRoute = 'vcard/import';
	elseif ($parent->id == 1) 	$targetRoute = 'site/import';
	elseif ($parent->id == 2) $targetRoute = 'stock/import';
	elseif ($parent->id == 3) $targetRoute = 'order/import';
	elseif ($parent->id == 4) $targetRoute = 'citUser/import'; ?>
<?php foreach ($links as $link) : ?>
        <tr class="<?php echo $this->cycle(array("even", "odd"))->next();?>">
                <td><a href="<?php echo $this->url('link/download', array('id' => $link->id));?>"><img height="12" src="/images/download_1.png" alt="<?php echo $this->translate('Download') ?>" /></a></td>
                <td><a href="<?php echo $this->url('link/delete', array('id' => $link->id));?>"><img height="12" src="/images/eraser.png" alt="<?php echo $this->translate('Delete') ?>" /></a></td>
                <td><a href="<?php echo $this->url($targetRoute, array('id' => $link->id));?>"><?php echo $this->translate('Import') ?></a></td>
                <td align="center"><a href="<?php echo $this->url('link/download', array('id' => $link->id));?>"><?php echo $link->name ?></a></td>
                <?php
                        $creationDate = strtotime($link->uploaded_time);
                        $creationDate = date("d/m/y g:i A", $creationDate);
                ?>
                <td align="center"><?php echo $creationDate ?></td>
        </tr>
<?php endforeach; ?>
</table>