<?php
    echo $this->partial('/partials/menu');
?>
<?php
$title = 'Add an order';
$this->headTitle($title);
?>
<h1><?php echo $this->translate($title); ?></h1>
<?php
    echo $this->partial('/partials/generic-form', array('route' => 'order/add', 'form' => $this->form, 'returnUrl' => $this->url('order')));
?>


<script>
function displayBrandModel() {
<?php foreach ($sites as $site) : ?>
	if (document.getElementById("site_id").value == "<?php echo $site->site_id ?>") {
		document.getElementById("nb_people").value = "<?php echo $site->nb_people ?>";
		document.getElementById("surface").value = "<?php echo $site->surface ?>";
		document.getElementById("nb_floors").value = "<?php echo $site->nb_floors ?>";
	}
<?php endforeach;?>
}
</script>