<html lang="fr">
    <head>
        <meta charset="utf-8">
        <title><?php echo $this->translate($title);?></title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
        <!-- Le styles -->
        <link href="/css/bootstrap.min.css" media="screen" rel="stylesheet" type="text/css">
<link href="/css/bootstrap-theme.min.css" media="screen" rel="stylesheet" type="text/css">
<link href="/css/style.css" media="screen" rel="stylesheet" type="text/css">
<link href="/img/favicon.ico" rel="shortcut icon" type="image/vnd.microsoft.icon">
        <!-- Scripts -->
        <!--[if lt IE 9]><script type="text/javascript" src="/js/html5shiv.js"></script><![endif]-->
<!--[if lt IE 9]><script type="text/javascript" src="/js/respond.min.js"></script><![endif]-->
<script type="text/javascript" src="/js/jquery.min.js"></script>
<script type="text/javascript" src="/js/bootstrap.min.js"></script>
    </head>
  <body>
	<?php $this->headTitle($title); ?>
	<h3 align="center"><?php echo $this->translate('Purchase order');?></h3>
	<table class=" class="table">
<?php foreach ($header as $element) : ?>
	<?php if ($element['label'] != 'Comment') : ?>
	    <tr>
			<td><strong><?php echo $this->translate($element['label']) ?></strong></td>
			<td><?php echo $element['value'] ?></td>
		</tr>
	<?php endif;?>
<?php endforeach;?>
	</table>
  </body>
</html>