<?php
    echo $this->partial('/partials/menu');
?>
<?php
$this->headTitle($title);
?>
<div class="row">
    <div class="col-md-6">
		<div class="panel panel-default">
            <div class="panel-heading">
				<strong><?php echo $this->translate($title);?></strong>
            </div>
           	<div class="panel-body">
<h3 align="center"><?php echo $this->translate('Site detail');?></h3>
<?php
    echo $this->partial('/partials/generic-display', array('header' => $header, 'returnUrl' => $this->url('site')));
?>
			</div>
		</div>
	</div>
</div>