<?php
    echo $this->partial('/partials/menu');
?>
<?php
$title = 'Site import';
$this->headTitle($title);
?>
<h1><?php echo $this->translate($title); ?></h1>
<?php if (!$ok) : ?>
<table class="table">
	<tr class="<?php echo $this->cycle(array("even", "odd"))->next();?>">
		<td style="color: red" colspan="3"><strong><?php echo $this->translate("Errors were found, the file cannot be imported:") ?></strong></td>
	</tr>
	<tr class="<?php echo $this->cycle(array("even", "odd"))->next();?>">
		<td align="center"><strong><?php echo $this->translate('Line number');?></strong></td>
		<td align="center"><strong><?php echo $this->translate('Column number');?></strong></td>
		<td align="left"><strong><?php echo $this->translate('Error');?></strong></td>
	</tr>
	<?php foreach ($errors as $error) : ?>
	<tr class="<?php echo $this->cycle(array("even", "odd"))->next();?>">
		<td align="center"><?php echo $error['line'] ?></td>
		<td align="center"><?php echo $error['column'] ?></td>
		<td align="left"><?php echo $this->translate($error['caption']) ?></td>
	</tr>
	<?php endforeach; ?>
</table>
<?php else : ?>
<table class ="table">
	<tr class="<?php echo $this->cycle(array("even", "odd"))->next();?>">
		<td align="center"><strong><?php echo $this->translate('SiteID');?></strong></td>
		<td align="center"><strong><?php echo $this->translate('Raison Sociale Livraison');?></strong></td>
		<td align="center"><strong><?php echo $this->translate('Siret Livraison');?></strong></td>
		<td align="center"><strong><?php echo $this->translate('Adresse');?></strong></td>
		<td align="center"><strong><?php echo $this->translate('Code Postal');?></strong></td>
		<td align="center"><strong><?php echo $this->translate('Ville');?></strong></td>
		<td align="center"><strong><?php echo $this->translate('Zone Géographique');?></strong></td>
		<td align="center"><strong><?php echo $this->translate('Siret Facturation');?></strong></td>
		<td align="center"><strong><?php echo $this->translate('Entité Facturation');?></strong></td>
		<td align="center"><strong><?php echo $this->translate('Effectif');?></strong></td>
		<td align="center"><strong><?php echo $this->translate('Superficie');?></strong></td>
		<td align="center"><strong><?php echo $this->translate('Nombre Etages');?></strong></td>
		<td align="center"><strong><?php echo $this->translate('Téléphone Site');?></strong></td>
		<td align="center"><strong><?php echo $this->translate('Horaires Logistique');?></strong></td>
		<td align="center"><strong><?php echo $this->translate('Contraintes Logistique');?></strong></td>
		<td align="center"><strong><?php echo $this->translate('Accessibilité Livraison');?></strong></td>
		<td align="center"><strong><?php echo $this->translate('Nom Contact principal');?></strong></td>
		<td align="center"><strong><?php echo $this->translate('Tel Contact principal');?></strong></td>
		<td align="center"><strong><?php echo $this->translate('Email Contact principal');?></strong></td>
		<td align="center"><strong><?php echo $this->translate('Nom Contact secondaire');?></strong></td>
		<td align="center"><strong><?php echo $this->translate('Tel Contact secondaire');?></strong></td>
		<td align="center"><strong><?php echo $this->translate('Email Contact secondaire');?></strong></td>
	</tr>
	<tr class="<?php echo $this->cycle(array("even", "odd"))->next();?>">
		<td colspan="13"><strong><?php echo $this->translate("The file is valid, the following rows will be imported:") ?></strong></td>
	</tr>
	<?php foreach ($not_duplicate as $row) : ?>
	<tr class="<?php echo $this->cycle(array("even", "odd"))->next();?>">
		<?php for ($i = 0; $i < count($row); $i++) : ?>
		<td align="center"><?php echo $row[$i] ?></td>
		<?php endfor;?>
	</tr>
	<?php endforeach; ?>
	<?php if (count($duplicate) > 0) : ?>
	<tr class="<?php echo $this->cycle(array("even", "odd"))->next();?>">
		<td colspan="13"><strong><?php echo $this->translate("The following rows already exist and will be ignored:") ?></strong></td>
	</tr>
	<?php endif;?>
	<?php foreach ($duplicate as $row) : ?>
	<tr class="<?php echo $this->cycle(array("even", "odd"))->next();?>">
	<?php for ($i = 0; $i < count($row); $i++) : ?>
		<td align="center"><?php echo $row[$i] ?></td>
	<?php endfor;?>
	</tr>
	<?php endforeach; ?>
</table>
<?php endif;?>
<?php $url = $this->url('site/import', array('id' => $this->id));?>
<form action="<?php echo $url; ?>" method="post">
<div>
    <input type="hidden" name="id" value="<?php echo (int) $this->id; ?>" />
    <input type="submit" class="btn btn-primary" name="confirm" value="<?php echo $this->translate('Import the data') ?>" />
    &nbsp;&nbsp;
	<a href="<?php echo $this->url('link/index', array ('id' => 1));?>"><?php echo $this->translate('Cancel') ?></a>
</div>
</form>
